### ISSUE TITLE
API is implemented using PHP

### ISSUE THREAD

**Issue by imgrey** [lacicloud/payiota#3]
Hello

The first major issue with PayIOTA API is that it written on PHP.

That is definitely a show stopper, as PHP has had many vulnerabilities in interpreter itself in past.

**Comment by lacicloud** [comment]
Hi!

I do not think this is a problem - the code is secure and so is PHP (just don't forget to always use the latest version). Facebook, Wordpress,  are all written in PHP. A programming language is only as ever good as it's master.

**Comment by imgrey** [comment]
Facebook has a huge budget to secure their application servers. Hardware firewalls, 5000+employees, etc. But even they have had issues in past.
Wordpress is just a remote execution shell.

There's no place for PHP in crypto/fintech industry.
